import Replicate from 'replicate';
import dotenv from 'dotenv';

dotenv.config();

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN!,
});

console.log('Replicate initialized with token:', process.env.REPLICATE_API_TOKEN ? `Yes (Length: ${process.env.REPLICATE_API_TOKEN.length})` : 'No');
if (process.env.REPLICATE_API_TOKEN && !process.env.REPLICATE_API_TOKEN.startsWith('r8_')) {
  console.warn('WARNING: Replicate token does not start with "r8_". It might be invalid.');
}

// The Nano Banana model on Replicate
const MODEL_ID = 'google/nano-banana';

// Face consistency prefix for custom prompts
export const FACE_CONSISTENCY_PREFIX = `Keep the facial features of the person in the uploaded image exactly consistent. Maintain 100% accuracy of the face from the reference image. Important: do not change the face. `;

// Edit prefix for refining existing portraits
export const EDIT_PREFIX = `Keep the person's face EXACTLY the same as in the uploaded image. Do not change any facial features, identity, or face structure. Only apply the following specific changes: `;

// Style prompts for professional headshots
export const STYLE_PROMPTS: Record<string, string> = {
  wine_bar: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a sophisticated, romantic wine bar portrait. The person wears elegant casual attire - a stylish burgundy or deep plum button-up shirt or silk blouse, dark fitted jeans or tailored trousers, minimal elegant jewelry. Expression: Warm, inviting, romantic with a genuine smile and engaging eye contact. Eyes show warmth and connection. Sophisticated date night energy. Pose: Sitting at a wine bar counter or intimate table, holding a glass of red wine elegantly. One elbow resting on bar, body turned slightly toward camera. Relaxed yet refined posture. Setting: Upscale wine bar with warm ambient lighting. Wooden bar counter with wine bottles artistically displayed on shelves behind. Soft bokeh of hanging Edison bulbs or pendant lights. Warm brick wall or dark wood paneling. Wine glasses and bottles creating elegant atmosphere. Lighting: Warm golden ambient lighting from bar and pendant lights creating intimate glow. Soft key light on face. Rim light separating subject from background. Romantic candlelight possible. Cinematic date night photography aesthetic. Composition: Medium portrait from waist up showing wine bar environment. Shallow depth of field with wine bar softly blurred into beautiful bokeh. Color palette: Deep burgundy and plum tones, rich wood browns, warm golden lighting, deep red wine, soft amber glows. Photography style: Romantic lifestyle editorial. Shot on 50mm f/1.8 lens with warm intimate lighting. High-detail fabric texture and wine glass reflections. Mood: Romantic, sophisticated, intimate. The perfect wine bar date night moment.`,
  with_supercar: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, high-fashion lifestyle photoshoot. The person is standing confidently next to a sleek, vibrant orange Lamborghini Aventador in a modern city setting at golden hour. The person wears a stylish black leather jacket, fitted dark jeans, designer sunglasses resting on head, and luxury sneakers. Expression: Confident, sophisticated, effortlessly cool with a subtle smile. Eyes show success and ambition. Luxury lifestyle energy. Pose: Leaning casually against the car with one hand on the hood, other hand in pocket. Confident stance with crossed ankles. Body angled toward camera. Setting: Modern urban environment with glass skyscrapers in background. Clean concrete or asphalt surface. Dramatic cityscape. Golden hour lighting creating warm glow. Lighting: Golden hour sunlight creating warm, flattering light. Car's metallic paint reflecting warm tones. Rim light separating subject from background. Cinematic automotive photography aesthetic. Composition: Medium to full-length portrait showing both person and car. Shallow depth of field with city softly blurred. Sharp focus on person and car details. Color palette: Vibrant orange car, black leather, warm golden hour tones, urban greys, blue sky. Photography style: High-end lifestyle editorial. Shot on 35mm lens with automotive photography techniques. High-detail car paint and leather texture. Mood: Luxurious, aspirational, successful. The ultimate lifestyle achievement moment.`,
  coffee_shop: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a warm, inviting coffee shop portrait. The person sits at a wooden table near a large window, holding a ceramic coffee cup with both hands. The person wears a cozy cream-colored knit sweater, dark jeans, casual watch. Expression: Warm, friendly, relaxed with a genuine smile. Eyes show contentment and approachability. Cozy weekend morning energy. Pose: Sitting comfortably at table, leaning slightly forward with elbows on table. Holding coffee cup near face. Natural, candid posture. Setting: Modern indie coffee shop with exposed brick walls, hanging plants, wooden furniture. Large windows letting in natural light. Coffee equipment and pastry display softly visible in background. Warm, inviting atmosphere. Lighting: Soft natural window light creating gentle shadows. Warm ambient lighting from overhead Edison bulbs. Golden morning light streaming through windows. Cozy café photography aesthetic. Composition: Medium portrait from waist up showing coffee shop environment. Shallow depth of field with café softly blurred into warm bokeh. Color palette: Warm cream sweater, rich coffee browns, natural wood tones, soft morning light, green plants. Photography style: Lifestyle editorial. Shot on 50mm f/1.8 lens with natural café lighting. High-detail knit texture and steam from coffee. Mood: Cozy, approachable, relaxed. The perfect coffee shop morning moment.`,
  luxury_yacht: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an elegant, sophisticated yacht lifestyle portrait. The person stands on the deck of a luxury white yacht with ocean in background. The person wears a flowing white linen dress or elegant white button-up shirt, gold jewelry, designer sunglasses, straw sun hat. Expression: Elegant, carefree, sophisticated with a radiant smile. Eyes show joy and luxury lifestyle. Breezy coastal elegance. Pose: Standing on yacht deck with one hand holding sun hat, other hand on yacht railing. Hair gently blowing in ocean breeze. Relaxed, elegant posture. Setting: Luxury yacht deck with white railings and teak wood flooring. Crystal blue ocean and sky in background. Bright sunny day. Yacht details like chrome fixtures and white cushions visible. Mediterranean or tropical setting. Lighting: Bright natural sunlight creating crisp, clean lighting. Ocean reflecting light for soft fill. Clear blue sky. High-key luxury photography aesthetic. Composition: Medium portrait showing yacht environment and ocean. Sharp focus on person with ocean creating beautiful blue background. Color palette: Crisp whites, ocean blues, warm skin tones, gold jewelry accents, natural teak wood. Photography style: Luxury travel editorial. Shot on 35mm lens with bright coastal lighting. High-detail fabric flow and jewelry sparkle. Mood: Elegant, luxurious, carefree. The ultimate yacht lifestyle experience.`,
  city_rooftop: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a sophisticated urban rooftop portrait at dusk. The person stands on a modern rooftop terrace with city skyline in background. The person wears a tailored navy blazer over a white t-shirt, dark fitted jeans, minimalist watch, clean white sneakers. Expression: Confident, urban, sophisticated with a knowing smile. Eyes show ambition and city energy. Modern professional energy. Pose: Standing with hands in pockets, body slightly angled. Confident urban stance. Or leaning casually against rooftop railing. Setting: Modern rooftop bar or terrace with glass railings, contemporary furniture, string lights. Dramatic city skyline with illuminated buildings in background. Dusk blue hour lighting. Urban plants and modern architecture. Lighting: Blue hour dusk lighting creating dramatic urban atmosphere. City lights beginning to glow. Soft ambient lighting from rooftop fixtures. Cinematic urban photography aesthetic. Composition: Medium to full portrait showing rooftop and city skyline. Shallow depth of field with city lights creating beautiful bokeh. Color palette: Navy blazer, white shirt, dusk blue sky, warm city lights, urban greys. Photography style: Urban lifestyle editorial. Shot on 35mm lens with city lights and blue hour lighting. High-detail blazer texture and city light bokeh. Mood: Sophisticated, urban, aspirational. The modern city professional lifestyle.`,
  beach_sunset: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a serene, magical beach sunset portrait. The person stands on a sandy beach with ocean waves and sunset in background. The person wears a flowing white or cream sundress, barefoot, minimal jewelry, hair naturally flowing in ocean breeze. Expression: Peaceful, joyful, free with a genuine smile. Eyes show serenity and happiness. Carefree beach energy. Pose: Standing with arms slightly spread or one hand touching hair. Natural, flowing movement. Dress and hair gently blowing in breeze. Relaxed beach posture. Setting: Beautiful sandy beach with gentle waves. Dramatic sunset with orange, pink, and purple sky. Ocean stretching to horizon. Wet sand reflecting sunset colors. Tropical or coastal paradise setting. Lighting: Golden hour sunset creating warm, magical glow. Backlit silhouette effect with rim lighting. Sunset reflecting off ocean and wet sand. Dreamy beach photography aesthetic. Composition: Medium to full portrait showing beach and sunset. Shallow depth of field with ocean and sunset creating stunning background. Color palette: Warm sunset oranges and pinks, cream dress, golden sand, ocean blues, purple sky. Photography style: Beach lifestyle editorial. Shot on 50mm lens with golden hour sunset lighting. High-detail fabric flow and hair movement. Mood: Peaceful, magical, free. The perfect beach sunset moment.`,
  executive_portrait: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a powerful, modern executive portrait. The person wears a sharp charcoal grey three-piece suit with subtle pinstripes, crisp white dress shirt, silk tie in deep burgundy, pocket square, luxury watch, polished black leather shoes. Expression: Confident, authoritative, approachable with a subtle knowing smile. Eyes show leadership and vision. Executive presence energy. Pose: Standing with arms crossed confidently, or one hand in pocket with the other adjusting cufflink. Strong, commanding posture. Body slightly angled. Setting: Modern executive office with floor-to-ceiling windows showing city skyline. Minimalist contemporary furniture. Dark wood desk. Leather executive chair. Modern art on walls. Professional corporate environment. Lighting: Soft directional window light creating depth. Subtle rim light for separation. Professional corporate photography lighting. Clean, crisp aesthetic. Composition: Medium to full portrait showing executive presence and office environment. Shallow depth of field with office softly blurred. Color palette: Charcoal suit, white shirt, burgundy tie, warm wood tones, city skyline blues, professional greys. Photography style: High-end corporate editorial. Shot on 85mm f/1.8 lens with professional lighting. High-detail suit texture and fabric weave. Mood: Powerful, confident, successful. The modern business leader.`,
  corporate_headshot: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a polished, professional corporate headshot. The person wears a tailored navy blue blazer over a crisp white blouse, minimal elegant jewelry (small earrings, delicate necklace), professional makeup, hair styled in elegant updo or sleek professional style. Expression: Confident, professional, approachable with a warm genuine smile. Eyes show competence and friendliness. Corporate professional energy. Pose: Shoulders angled slightly, facing camera directly. Arms not visible (tight headshot). Professional posture with excellent presence. Setting: Clean corporate studio backdrop in neutral grey or soft blue. Professional photography studio setup. Simple, distraction-free background. Lighting: Classic three-point lighting creating soft, flattering illumination. Catchlights in eyes. No harsh shadows. Professional headshot lighting. Composition: Tight headshot from shoulders up with ample headroom. Sharp focus on eyes. Professional corporate photography framing. Color palette: Navy blazer, crisp white, neutral background, warm skin tones, professional polish. Photography style: Corporate headshot photography. Shot on 85mm f/2.0 lens with studio lighting. High-detail fabric texture and professional finish. Mood: Professional, competent, approachable. The perfect corporate headshot.`,
  startup_founder: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a modern, innovative startup founder portrait. The person wears smart casual attire - tailored blazer in navy or charcoal over a premium t-shirt or casual button-up, dark fitted jeans, minimalist sneakers or casual leather shoes, modern watch or tech accessories. Expression: Visionary, innovative, energetic with a confident smile. Eyes show passion and determination. Startup founder energy. Pose: Leaning casually against modern desk or standing with hands in pockets. Relaxed yet confident posture. Modern professional stance. Setting: Modern startup office with exposed brick, industrial elements, standing desks, monitors with code or designs, whiteboard with ideas, plants, contemporary furniture. Tech startup aesthetic. Lighting: Natural window light mixed with modern office lighting. Bright, energetic atmosphere. Contemporary photography style. Composition: Medium portrait showing startup environment. Shallow depth of field with office creating modern bokeh. Color palette: Smart casual blazer, premium basics, modern office colors, tech aesthetic, natural light tones. Photography style: Modern business editorial. Shot on 35mm lens with natural lighting. High-detail casual professional texture. Mood: Innovative, energetic, visionary. The modern tech entrepreneur.`,
  business_casual: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a smart casual professional portrait. The person wears modern business casual - tailored blazer in camel or soft grey over a silk camisole or quality t-shirt, tailored trousers or dark jeans, minimal elegant jewelry, professional yet relaxed styling. Expression: Confident, modern, approachable with a natural smile. Eyes show professionalism and warmth. Smart casual energy. Pose: Standing with one hand on hip, other holding tablet or coffee. Or sitting on desk edge. Relaxed professional posture. Setting: Modern open office with natural light, contemporary furniture, plants, collaborative workspace. Bright, airy professional environment. Lighting: Abundant natural window light creating bright, fresh atmosphere. Soft shadows. Modern workplace photography aesthetic. Composition: Medium portrait showing modern workplace. Shallow depth of field with office softly blurred. Color palette: Soft blazer tones, quality basics, modern office whites and greys, natural light, fresh professional aesthetic. Photography style: Modern workplace editorial. Shot on 50mm f/1.8 lens with natural lighting. High-detail smart casual texture. Mood: Modern, professional, approachable. The contemporary workplace professional.`,
  conference_speaker: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a dynamic conference speaker portrait. The person wears professional presentation attire - well-fitted suit in navy or charcoal, or smart blazer with dress shirt (no tie for modern look), lapel microphone visible, professional watch. Expression: Engaging, confident, passionate with animated expression. Eyes show expertise and enthusiasm. Speaker energy. Pose: Mid-gesture while presenting - hand raised making a point, or holding presentation clicker. Dynamic, engaging posture. Body language shows confidence. Setting: Professional conference stage with presentation screen or backdrop behind. Soft stage lighting. Professional conference environment. Audience slightly visible and blurred in background. Lighting: Professional stage lighting with key light on speaker. Soft fill light. Rim light for separation. Conference photography aesthetic. Composition: Medium portrait showing speaker in action. Shallow depth of field with conference environment softly blurred. Color palette: Professional suit, stage lighting, conference blues and greys, professional presentation aesthetic. Photography style: Conference photography. Shot on 50mm lens with stage lighting. High-detail capturing speaker in action. Mood: Engaging, authoritative, dynamic. The professional thought leader.`,
  candlelit_dinner: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a romantic, intimate candlelit dinner portrait. The person wears an elegant dress in deep red or burgundy with sophisticated neckline, delicate gold jewelry (necklace, earrings), elegant updo or soft romantic waves, subtle makeup with emphasis on eyes. Expression: Romantic, warm, inviting with a soft genuine smile. Eyes show warmth and connection. Intimate dinner date energy. Pose: Sitting at intimate table for two, leaning forward slightly with one hand near wine glass, other hand resting elegantly. Engaged, romantic posture. Setting: Upscale romantic restaurant with dim ambient lighting. White tablecloth, elegant place settings, wine glasses, small floral centerpiece. Candles on table creating warm glow. Soft bokeh of other diners and restaurant ambiance in background. Lighting: Warm candlelight as primary light source creating intimate glow on face. Soft ambient restaurant lighting. Romantic golden tones. Cinematic dinner date photography aesthetic. Composition: Medium portrait from waist up showing romantic dinner setting. Shallow depth of field with restaurant softly blurred into beautiful bokeh. Color palette: Deep red or burgundy dress, warm candlelight, gold jewelry, white tablecloth, rich restaurant ambiance. Photography style: Romantic lifestyle editorial. Shot on 50mm f/1.8 lens with candlelight and ambient lighting. High-detail fabric texture and jewelry sparkle. Mood: Romantic, intimate, elegant. The perfect candlelit dinner date.`,
  sunset_walk: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a romantic golden hour walk portrait. The person wears casual romantic attire - fitted henley shirt or casual button-up in earth tones (olive, tan, navy), dark jeans, casual watch, relaxed styling. Expression: Warm, genuine, romantic with a natural smile. Eyes show happiness and connection. Romantic walk energy. Pose: Walking casually with hands in pockets or one hand running through hair. Natural, candid movement. Relaxed, approachable posture. Setting: Beautiful outdoor setting during golden hour - tree-lined path, park, or waterfront. Warm sunset light filtering through trees or reflecting off water. Natural romantic environment. Lighting: Golden hour sunlight creating warm, romantic glow. Backlit with rim lighting creating halo effect. Soft shadows. Dreamy romantic photography aesthetic. Composition: Medium to full portrait showing romantic outdoor setting. Shallow depth of field with background creating golden bokeh. Color palette: Warm earth tones, golden sunset light, natural greens, soft romantic colors. Photography style: Romantic lifestyle editorial. Shot on 50mm lens with golden hour natural lighting. High-detail fabric texture and natural light. Mood: Romantic, natural, warm. The perfect sunset walk moment.`,
  cozy_date_night: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a cozy, intimate home date night portrait. The person wears comfortable yet stylish attire - soft cashmere sweater in cream or blush pink, comfortable jeans or lounge pants, minimal jewelry, natural relaxed styling with soft waves. Expression: Warm, comfortable, intimate with a genuine smile. Eyes show contentment and connection. Cozy date night energy. Pose: Sitting on couch with legs tucked, holding mug of hot chocolate or tea with both hands. Relaxed, comfortable, intimate posture. Setting: Cozy living room with soft throw blankets, cushions, warm lighting. Fireplace or candles visible. String lights or soft lamps. Books, plants, comfortable home atmosphere. Lighting: Warm ambient lighting from lamps and candles. Soft, diffused light creating cozy atmosphere. Golden warm tones. Intimate home photography aesthetic. Composition: Medium portrait showing cozy home environment. Shallow depth of field with living room softly blurred. Color palette: Soft cream and blush tones, warm lighting, natural wood, cozy home colors. Photography style: Lifestyle editorial. Shot on 50mm f/1.8 lens with warm ambient lighting. High-detail soft fabric texture. Mood: Cozy, intimate, comfortable. The perfect home date night.`,
  romantic_picnic: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a romantic outdoor picnic portrait. The person wears casual romantic attire - light blue or white linen shirt (sleeves rolled up), khaki or tan chinos, casual watch, relaxed summer styling. Expression: Happy, carefree, romantic with a bright genuine smile. Eyes show joy and warmth. Romantic picnic energy. Pose: Sitting on picnic blanket, leaning back on one hand, other hand holding wine glass or reaching for food. Relaxed, happy posture. Setting: Beautiful park or meadow with lush green grass. Picnic blanket with basket, wine, cheese, fruits. Trees in background. Bright sunny day. Natural romantic outdoor setting. Lighting: Bright natural sunlight with soft shadows. Dappled light through trees. Fresh, bright outdoor photography aesthetic. Composition: Medium portrait showing picnic setting and natural environment. Shallow depth of field with park softly blurred. Color palette: Light blue or white shirt, natural greens, picnic basket browns, bright outdoor colors. Photography style: Romantic lifestyle editorial. Shot on 35mm lens with natural outdoor lighting. High-detail fabric texture and natural setting. Mood: Happy, romantic, carefree. The perfect romantic picnic.`,
  jazz_club_date: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a sophisticated jazz club date portrait. The person wears elegant evening attire - sleek black dress or satin blouse with tailored trousers, statement jewelry (gold or pearl earrings), elegant styling with vintage-inspired waves or sleek updo, classic makeup. Expression: Sophisticated, confident, romantic with a knowing smile. Eyes show elegance and allure. Jazz club sophistication energy. Pose: Sitting at intimate jazz club table, leaning forward with one elbow on table, hand near cocktail glass. Elegant, sophisticated posture. Setting: Intimate jazz club with dim moody lighting. Small round table with cocktail glass, candle. Stage with musicians softly visible in background. Vintage jazz club aesthetic with dark wood and leather. Lighting: Moody low-key lighting with warm amber tones. Spotlight creating dramatic shadows. Candlelight on table. Cinematic jazz club photography aesthetic. Composition: Medium portrait showing jazz club atmosphere. Shallow depth of field with club and stage softly blurred. Color palette: Black dress, warm amber lighting, gold jewelry, dark rich jazz club tones. Photography style: Cinematic lifestyle editorial. Shot on 50mm f/1.8 lens with moody club lighting. High-detail fabric texture and jewelry. Mood: Sophisticated, elegant, romantic. The perfect jazz club date night.`,
  // Business Photo style
  business: `Keep the facial features of the person in the uploaded image exactly consistent. Dress them in a professional navy blue business suit with a white shirt, similar to the reference image. Background: Place the subject against a clean, solid dark gray studio photography backdrop. The background should have a subtle gradient, slightly lighter behind the subject and darker towards the edges (vignette effect). There should be no other objects. Photography Style: Shot on a Sony A7III with an 85mm f/1.4 lens, creating a flattering portrait compression. Lighting: Use a classic three-point lighting setup. The main key light should create soft, defining shadows on the face. A subtle rim light should separate the subject's shoulders and hair from the dark background. Crucial Details: Render natural skin texture with visible pores, not an airbrushed look. Add natural catchlights to the eyes. The fabric of the suit should show a subtle wool texture. Final image should be an ultra-realistic, 8k professional headshot.`,

  // Cinematic Tight Portrait
  tight_portrait: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a tight portrait crop from upper torso to head in vertical orientation. Composition: Subject placed slightly right of center with shoulders angled and head turned toward camera at eye-level. Shallow depth of field with smooth background falloff. Soft negative space on left side created by gradient background. Subject: Three-quarter profile with subtle head tilt. Serious, confident, introspective expression with gaze directed slightly past the camera. Sharp jawline, defined cheekbones, light stubble. Short, dark, neatly styled hair with slight texture. High-detail skin with visible pores and natural highlights. Wardrobe: Black or very dark charcoal knit zip-up sweater with heavy ribbed knit fabric texture. Slim fit with high collar partially zipped. Minimalist, modern, masculine style. Lighting: Strong directional light from front-left with minimal fill allowing deep shadows. Subtle rim light for edge separation along jaw and shoulder. High contrast with dramatic shadow sculpting. Soft but directional, cinematic light quality with controlled specular highlights on skin. Color Palette: Deep red, burgundy, and black dominant colors. Warm, slightly desaturated skin tones. Moody and cinematic overall tone with warm shadows and subtle red cast color grading. Background: Dark red gradient studio backdrop with smooth texture and soft light diffusion. Clear subject-background separation via lighting and contrast. Technical: Short telephoto portrait lens look (85mm equivalent). Wide aperture style (f/1.8–f/2.8). High facial sharpness with smooth background blur. Minimal noise, clean studio image with controlled highlights and rich shadows. Artistic Style: Fashion portrait / cinematic editorial genre. Intense, refined, dramatic mood. Luxury, high-fashion, modern masculinity aesthetic with cinematic lighting influences. Post-Processing: Subtle skin retouching preserving texture. Enhanced midtone contrast. Warm red-toned grade with muted saturation. Very subtle edge darkening vignette.`,

  // Luxury Fashion Editorial
  luxury_fashion: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Design a dark, cinematic portrait featuring a powerful, refined alpha male with luxury fashion editorial lighting and a moody, romantic tone. Subject: Handsome alpha male with dominant, controlled, mysterious presence. Facial features: Smoldering, intense, restrained expression. Gaze looking downward, partially obscured by shadow. Clean, smooth skin with no tattoos. High-detail facial structure. Pose: Adjusting the cufflink on one sleeve of white dress shirt. Body language: Confident, composed, quietly powerful. Wardrobe: Sharp tailored black suit, crisp white dress shirt, dark tie. Luxury, classic, high-status mafia aesthetic. Scene and Background: Pure black background. Minimalist studio setup. Dark, moody, seductive, elite atmosphere. Lighting: Cinematic soft directional lighting angled to sculpt the face and suit. Very subtle fill to preserve shadow depth. Face partially in shadow with smooth tonal transitions. Continuous tonal gradients across the face. Intense, luxurious, emotionally charged mood. Composition: Medium portrait framing from torso to head. Centered composition with strong vertical symmetry. Subject perfectly centered in frame. Ample dark space around subject. Photography Style: Luxury fashion editorial / cinematic portrait. Dark mafia romance aesthetic. High-end studio photography. Color and Grading: Deep blacks, charcoal shadows, soft neutral skin tones, clean white highlights. Low-key cinematic grading with controlled highlights and deep blacks. Detail: High-detail suit texture and fabric folds. Photorealistic, film-quality realism. Polished, premium quality finish.`,

  // Emotional Film Photography style
  emotional_film: `Keep the facial features of the person in the uploaded image exactly consistent. Style: A cinematic, emotional portrait shot on Kodak Portra 400 film. Setting: An urban street coffee shop window at Golden Hour (sunset). Warm, nostalgic lighting hitting the side of the face. Atmosphere: Apply a subtle film grain and soft focus to create a dreamy, storytelling vibe. Action: The person is looking slightly away from the camera, holding a coffee cup, with a relaxed, candid expression. Details: High quality, depth of field, bokeh background of city lights.`,

  // Victoria's Secret Photoshoot style
  victoria_secret: `Create a glamorous photoshoot in the style of Victoria's Secret. The person in the uploaded reference image (Keep the face of the person 100% accurate from the reference image) stands almost sideways, slightly bent forward, during the final preparation for the show. Makeup artists apply lipstick (only their hands are visible in the frame). The person is wearing a corset decorated with beaded embroidery and crystals with a short fluffy skirt, as well as large feather wings. The image has a "backstage" effect. The background is a darkly lit room, probably under the podium. The main emphasis is on the person's face and the details of the costume. Emphasize the expressiveness of the gaze and the luxurious look of the outfit. The photo is lit by a flash from the camera, which emphasizes the shine of the beads and crystals on the corset, as well as the shiny skin. Victoria's Secret style: sensuality, luxury, glamour. Very detailed. Important: do not change the face.`,

  // 1990s Camera Style
  nineties_camera: `Without changing their original face, create a portrait of a beautiful person with porcelain-white skin, captured with a 1990s-style camera using a direct front flash. Her messy dark brown hair is tied up, posing with a calm yet playful smile. She wears a modern oversized cream sweater. The background is a dark white wall covered with aesthetic magazine posters and stickers, evoking a cozy bedroom or personal room atmosphere under dim lighting. The 35mm lens flash creates a nostalgic glow.`,

  // Professional Headshot
  professional_headshot: `A professional, high-resolution profile photo, maintaining the exact facial structure, identity, and key features of the person in the input image. The subject is framed from the chest up, with ample headroom. The person looks directly at the camera. They are styled for a professional photo studio shoot, wearing a premium smart casual blazer in a subtle charcoal gray. The background is a solid '#562226' neutral studio color. Shot from a high angle with bright and airy soft, diffused studio lighting, gently illuminating the face and creating a subtle catchlight in the eyes, conveying a sense of clarity. Captured on an 85mm f/1.8 lens with a shallow depth of field, exquisite focus on the eyes, and beautiful, soft bokeh. Observe crisp detail on the fabric texture of the blazer, individual strands of hair, and natural, realistic skin texture. The atmosphere exudes confidence, professionalism, and approachability. Clean and bright cinematic color grading with subtle warmth and balanced tones, ensuring a polished and contemporary feel.`,

  // With Puppy
  with_puppy: `The person's facial features, expression, and identity must remain exactly the same as the reference image. Preserve the original face completely. The person is outdoors in a winter scene, puckering their lips toward the camera in a playful, cute expression. They are wearing a black hooded sweatshirt and holding a small white puppy with light blue eyes. The puppy has a calm expression, looking forward. Environment: outdoors in a winter scene with snow covering the ground, bare trees in the background, and a blurred vehicle behind the person. The sky is a clear light blue. Mood: cute, natural, winter outdoor moment. Camera style: soft depth of field, natural daylight, subtle winter tones. The composition captures a heartwarming moment between the person and the adorable puppy.`,

  // With Pikachu
  pikachu: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, professional fashion photoshoot. The person is wearing an electric yellow knitted sweater, black high-waisted jeans, and white high-top sneakers with black accents. The person is standing casually with their arm resting on a giant 3D photorealistic Pikachu character beside them. Pikachu should be rendered in ultra-realistic 3D with accurate proportions, textures, and the iconic red cheeks, smiling up at the person with a cheerful expression. The person has an energetic, cheerful expression. Environment: vibrant yellow backdrop with professional studio lighting. The lighting creates soft shadows and highlights the texture of the knitted sweater. Camera: Shot on a high-end fashion camera with shallow depth of field. The composition captures a fun, playful interaction between the person and the beloved Pokémon character in a modern, stylish photoshoot aesthetic.`,

  // With Tom & Jerry
  tom_and_jerry: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, professional fashion photoshoot. The person is wearing a light grey knitted sweater, blue high-waisted jeans, and white high-top sneakers. The person is standing with their arm around a giant 3D photorealistic Tom Cat character. Tom should be rendered in ultra-realistic 3D while maintaining his iconic cartoon appearance - grey and white fur, posing confidently with a mischievous smirk. On Tom's shoulder sits Jerry Mouse, also in 3D photorealistic style with his characteristic brown fur and playful expression. The person has a fun, mischievous expression. Environment: clean grey-blue backdrop with professional studio lighting. Camera: Shot on a high-end fashion camera with perfect focus on all three subjects. The composition captures the playful dynamic between the person and the classic cartoon duo in a modern photoshoot style.`,

  // With Ben 10
  ben_ten: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, professional fashion photoshoot with sci-fi hero aesthetics. The person is wearing a Ben 10 themed green and black sweater, dark grey jeans, and white sneakers with green accents. The person is standing confidently beside a giant 3D photorealistic render of Ben Tennyson (Classic Ben 10 character) who is activating his Omnitrix. Ben should be rendered in ultra-realistic 3D with cartoon accuracy - wearing his iconic green jacket with the number 10, black shirt, cargo pants, and the glowing green Omnitrix device on his wrist. The Omnitrix emits a dynamic bright green glow. The person has a confident, energetic expression. Environment: neon-green and black circuitry patterns backdrop, with dynamic green glow reflecting from the Omnitrix onto both subjects. The lighting creates a sci-fi hero fashion shoot mood. Camera: Shot on a high-end fashion camera with professional lighting that emphasizes the dramatic green glow. The composition captures an action-ready, superhero-inspired moment.`,

  // With Pink Panther
  pink_panther: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, professional fashion photoshoot. The person is wearing a pastel pink knitted sweater, white high-waisted jeans, and white sneakers with pink accents. The person is posing fashionably beside a tall giant 3D photorealistic Pink Panther character. The Pink Panther should be rendered in ultra-realistic 3D with accurate iconic features - bright pink fur, elongated body, distinctive snout, and characteristic cool, suave posture striking a stylish pose with one paw raised. The person has an elegant, stylish expression. Environment: light pastel pink backdrop with soft, flattering professional studio lighting. The lighting creates a dreamy, fashionable atmosphere. Camera: Shot on a high-end fashion camera with shallow depth of field and perfect focus. The composition captures a sophisticated, fashion-forward moment with the legendary cool character in a modern editorial style.`,

  // With Bulbasaur
  bulbasaur: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, premium studio fashion shoot with designer-toy finish. The person is wearing a mint-green knitted sweater, off-white high-waisted jeans, and white high-top sneakers with subtle green accents. The person is standing with one hand naturally resting near the bud area on a giant 3D photorealistic Bulbasaur (not covering faces), the other hand lightly on the waist. The person has a playful, lively, mischievous smile. Bulbasaur should be rendered as a giant 3D photorealistic character with a cute yet realistic, premium vinyl-toy look - clean skin micro-texture, refined bud material detail, clear glossy eyes, and crisp silhouette. Bulbasaur tilts its head up slightly toward the person with a gentle, friendly photo-op vibe. Environment: clean mint gradient studio backdrop, minimal. Lighting: soft key light plus subtle rim light, porcelain-fair clean skin rendering, crisp shadows. Composition: full-body or 3/4 fashion-ad framing with generous negative space, premium street-editorial vibe.`,

  // With Charmander
  charmander: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, premium studio fashion shoot with designer-toy finish. The person is wearing a vibrant orange-red knitted sweater, deep black high-waisted jeans, and white high-top sneakers with subtle orange accents. The person is standing with their arm casually leaning on a giant 3D photorealistic Charmander's shoulder or back area, body slightly angled for a stronger silhouette. The person has an energetic, confident, cheeky smile. Charmander should be rendered as a giant 3D photorealistic character with controlled warm glow accents - refined skin detail, tail flame realistic but not overpowering, clear glossy eyes. Charmander wears a proud expression, and the tail flame adds a subtle warm rim-light reflection on the person. Environment: high-saturation orange-red gradient backdrop, minimal fashion studio. Lighting: studio key light plus subtle warm rim from tail flame, clean premium finish. Composition: 3/4 body framing with bold color-block impact, commercial fashion vibe.`,

  // With Squirtle
  squirtle: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, premium studio fashion shoot with designer-toy finish. The person is wearing a sea-salt blue knitted sweater, light grey high-waisted jeans, and white high-top sneakers with subtle blue accents. The person is standing with one hand lightly resting on the edge of a giant 3D photorealistic Squirtle's shell, the other hand relaxed. The person has a fresh, cute, slightly cool expression. Squirtle should be rendered as a giant 3D photorealistic character with a glossy-toy yet realistic finish - premium semi-gloss shell material, clean skin micro-detail, clear glossy eyes. Squirtle holds a relaxed signature smile pose, creating a crisp monochrome duo aesthetic. Environment: clean light-blue gradient studio backdrop, minimal. Lighting: soft key light plus delicate rim, porcelain-fair clean skin rendering. Composition: full-body or 3/4 framing with airy negative space, refined clean look.`,

  // With Jigglypuff
  jigglypuff: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a hyper-realistic, soft pastel editorial, premium studio fashion shoot. The person is wearing a pastel lavender-pink knitted sweater, creamy off-white high-waisted jeans, and white/pink high-top sneakers. The person is in a stylish standing pose, gently leaning beside a giant 3D photorealistic Jigglypuff. Jigglypuff does a cute photo gesture with a small wave or hands-on-cheeks. The person has a soft, sweet, elegant expression. Jigglypuff should be rendered as a giant 3D photorealistic character with a premium plush-toy vibe - subtle fuzzy surface, clean noise-free finish, clear glossy eyes, high-end designer-toy look. Jigglypuff smiles and waves slightly, creating a cute-yet-premium duo mood. Environment: light pastel lavender-pink gradient backdrop with extremely subtle paper-like texture. Lighting: diffused soft light, clean translucent skin rendering, airy mood. Composition: magazine-cover style framing with generous negative space, refined sweetness.`,

  // Zootopia Cable Car
  zootopia_cable_car: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a cozy, cinematic winter scene inside a glass cable car in the Swiss Alps. The person is wearing a red knit sweater and blue jeans, sitting on a wooden bench, smiling softly at the camera with long dark hair and a warm, natural look. On the person's left, Nick Wilde from Zootopia, the sly red fox character, leans in relaxed wearing his green shirt and striped tie with a confident smirk. On the person's right, Judy Hopps from Zootopia, the cheerful gray rabbit police officer in her blue uniform, sits close with an energetic, friendly expression. The person has their arms around both characters, creating a wholesome, affectionate moment. Nick Wilde and Judy Hopps should be rendered as high-quality photorealistic 3D animated characters that blend seamlessly with the real person. Outside the cable car window, snow-covered mountains stretch into the distance under a clear blue sky, with a red alpine train crossing a stone bridge in the background. Environment: bright natural daylight, crisp winter atmosphere, ultra-detailed glass cable car interior with wooden benches. Lighting: soft natural light from windows, gentle shadows. Composition: cozy travel aesthetic with sharp focus, 4:5 aspect ratio, high resolution. The scene should feel warm and wholesome despite the cold winter setting outside.`,

  // Magazine Cover
  magazine_cover: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a high-fashion magazine cover shot of a stunning woman sitting on the hood of a vintage car. Subject Details: Woman in her 20s with platinum blonde hair styled in a sleek low side ponytail with deep side part and smooth texture. Expression: Piercing direct eye contact with confident, enigmatic, intense energy. Eyes looking straight at camera. Mouth slightly parted and relaxed. Overall sophisticated, bold, effortlessly chic expression. Face: Natural glam makeup with sculpted cheekbones, subtle eyeliner, matte nude lip. High-resolution realistic skin pores and texture. Fair pale skin tone with sun-kissed bright highlights. Pose: Sitting on a vintage car hood with legs crossed, one foot resting on car, one leg bent underneath. Hand resting elegantly on chin/jawline, leaning slightly forward with commanding presence. Slender high-fashion model physique with visible collarbones. Clothing: Oversized blazer over a black bralette. Heather grey blazer with black abstract/floral appliqué patches, textured wool blend, structured shoulders, open front - tailored yet relaxed. No pants visible (bare legs focus). Smooth skin texture on legs. Black strappy high heels with glossy finish and ankle straps. Setting: Outdoor driveway or garden. Vintage gold or metallic bronze car hood with shiny finish, classic muscle car aesthetic. Background: Blurred green trees, bright sky hints, natural greens. Luxurious sunny spring day atmosphere with dappled sunlight in background. Photography: High-end editorial fashion photography, magazine cover style. Eye-level or slightly low angle. Full body medium shot, center weighted. Sharp focus on subject with glossy magazine print quality. Bright natural sunlight with hard daylight, strong contrast, and distinct shadows. Shallow depth of field with bokeh background. 4:5 aspect ratio. Vibe: Magnetic and empowering energy. Sophisticated, cool, expensive mood. Classic editorial celebrity portraiture aesthetic. Polished professional shoot. A star at the height of her power, basking in the spring sun, redefining modern elegance.`,

  // Executive Chef
  executive_chef: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a cinematic portrait of an executive chef in a high-end modern kitchen. The person wears a pristine white chef's coat with sharp creases and professional tailoring, black apron tied at the waist. Arms crossed confidently or hands clasped in front, holding a chef's knife with authority. Expression: Focused, passionate, confident with a slight knowing smile. Eyes show intensity and mastery of craft. Setting: Modern professional kitchen with stainless steel surfaces, soft bokeh of kitchen equipment in background. Warm ambient lighting from overhead pendant lights mixed with cool stainless steel reflections. Dramatic side lighting creates depth and highlights the chef's coat texture. Composition: Medium portrait from waist up, slightly off-center with kitchen elements visible. Steam rising subtly in the background adds atmosphere. Color palette: Clean whites, warm golds, stainless steel silvers, with pops of fresh ingredient colors softly blurred in background. Photography style: Editorial culinary magazine cover aesthetic. Shot on 50mm lens with shallow depth of field. Professional food photography lighting - soft but dramatic. High-detail fabric texture on chef's coat. Mood: Sophisticated, passionate, masterful. The portrait of a culinary artist at the peak of their craft.`,

  // Airline Pilot
  airline_pilot: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a powerful portrait of a commercial airline pilot in the cockpit during golden hour. The person wears a sharp navy blue pilot uniform with gold epaulettes showing captain's stripes, crisp white shirt, black tie, and pilot's cap with gold emblem. Aviator sunglasses rest on the instrument panel or worn stylishly. Expression: Calm, confident, authoritative with a subtle professional smile. Eyes convey trust and competence. Pose: Seated in captain's seat, one hand on the control yoke, body turned slightly toward camera. Professional yet approachable posture. Setting: Modern aircraft cockpit with illuminated instruments and displays creating ambient blue and orange glows. Large cockpit windows show golden hour sky with dramatic clouds and sunset colors. Lighting: Warm golden hour sunlight streaming through cockpit windows, creating rim lighting on the uniform. Instrument panel lights add cool blue accent lighting to face. Cinematic aviation photography aesthetic. Composition: Medium portrait showing upper body and partial cockpit environment. Shallow depth of field with sharp focus on pilot, softly blurred instrument panels. Color palette: Navy blue uniform, gold accents, warm sunset oranges and pinks, cool instrument blues. Photography style: High-end aviation editorial. Shot on 35mm lens. Professional dramatic lighting. Mood: Inspiring, adventurous, trustworthy. The embodiment of aviation excellence and the dream of flight.`,

  // Surgeon
  surgeon: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a dramatic portrait of an elite surgeon in a modern operating room. The person wears surgical scrubs in deep teal or navy blue, surgical cap, with a stethoscope draped around neck. Surgical mask pulled down to chin or held in hand, revealing face. Expression: Focused, intelligent, compassionate with determined eyes. A look of both intensity and care. Slight confident expression showing mastery and dedication. Pose: Standing with arms crossed holding surgical gloves, or hands clasped in front in a thoughtful pose. Confident professional stance. Setting: Modern operating room with surgical lights creating dramatic overhead illumination. Blurred medical equipment and monitors in background showing vital signs displays. Sterile blue-green color tones from surgical environment. Lighting: Dramatic overhead surgical lights creating strong directional lighting from above. Cool blue-green ambient light from OR environment. Rim lighting separating subject from background. Cinematic medical drama aesthetic. Composition: Medium portrait from waist up, centered with OR environment visible. Sharp focus on surgeon with softly blurred medical equipment. Color palette: Deep teal scrubs, surgical blues and greens, stainless steel, with warm skin tones contrasting cool environment. Photography style: Medical drama editorial. Shot on 50mm lens with dramatic lighting. High-detail fabric texture on scrubs. Mood: Heroic, dedicated, life-saving. The portrait of a medical professional at the height of their calling.`,

  // Creative Artist
  creative_artist: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a vibrant portrait of a contemporary artist in their creative studio. The person wears paint-splattered denim shirt or black turtleneck with rolled-up sleeves, casual jeans with artistic stains. Hands show traces of paint on fingers. Expression: Passionate, thoughtful, inspired with a creative spark in the eyes. Slight smile showing love for their craft. Authentic artistic energy. Pose: Standing with arms crossed holding a paintbrush, or sitting casually on a stool with paint palette in hand. Relaxed yet engaged posture. One hand touching chin in contemplative gesture. Setting: Artist's studio with large canvases visible in background, paint tubes and brushes scattered artistically. Colorful abstract paintings partially visible. Natural light streaming through large industrial windows. Exposed brick or white walls with paint splatters. Lighting: Soft natural window light creating beautiful side lighting. Warm golden hour glow mixed with cool studio shadows. Paint colors in background create vibrant bokeh. Artistic documentary photography aesthetic. Composition: Medium portrait showing upper body and studio environment. Shallow depth of field with colorful artistic chaos softly blurred behind. Color palette: Vibrant paint colors - reds, blues, yellows, greens creating artistic energy. Warm skin tones. Denim blues or black clothing contrasting colorful background. Photography style: Documentary art editorial. Shot on 35mm lens. Natural light with artistic flair. Mood: Inspired, free-spirited, passionate. The portrait of a creative soul in their element, surrounded by the beauty of artistic expression.`,

  // Firefighter Hero
  firefighter_hero: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a powerful heroic portrait of a firefighter after a successful rescue. The person wears full firefighter turnout gear - heavy tan/beige protective coat with reflective yellow stripes, fire helmet with shield, but coat is partially open showing dark t-shirt underneath. Face shows slight soot marks adding authenticity. Helmet held under one arm or worn pushed back. Expression: Strong, brave, determined yet compassionate. Eyes show courage and dedication. Slight proud smile of someone who saves lives. Authentic hero energy. Pose: Standing confidently with arms crossed or one hand on hip, other holding helmet. Strong heroic stance. Shoulders back, commanding presence. Setting: Fire truck in background with red lights creating dramatic ambient glow. Subtle smoke or mist in air adding atmosphere. Fire station bay or outdoor scene with emergency vehicle. Golden hour or dramatic twilight lighting. Lighting: Dramatic side lighting with warm golden tones. Red emergency lights creating accent lighting and rim light. Slight haze in air catching light beams. Cinematic action movie aesthetic. Composition: Medium to full portrait showing firefighter gear and fire truck background. Shallow depth of field with fire truck and smoke softly blurred. Color palette: Tan firefighter gear, reflective yellow stripes, red fire truck, warm golden light, cool blue shadows. Photography style: Cinematic hero portrait. Shot on 35mm lens with dramatic lighting. High-detail gear texture. Mood: Heroic, brave, inspiring. The portrait of an everyday hero who runs toward danger to save lives. Powerful and emotionally moving.`,

  // WINTER STYLES
  cozy_cabin: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a warm, cozy winter portrait in a rustic cabin setting. The person wears an oversized chunky knit cream or caramel sweater with cable knit texture. Holding a steaming mug of hot cocoa or coffee with both hands. Expression: Warm, content, peaceful with a gentle smile. Eyes convey comfort and relaxation. Authentic cozy hygge energy. Pose: Sitting comfortably wrapped in the sweater, hands around warm mug. Relaxed, intimate posture. Legs tucked up on cozy chair or sofa. Setting: Rustic wooden cabin interior with stone fireplace visible in soft background. Warm glowing fire creating ambient orange light. Soft plaid blanket nearby. Frosted window showing snow outside. Wood beam ceiling. Lighting: Warm fireplace glow as key light creating golden tones on face. Soft ambient cabin lighting. Rim light separating subject from background. Cozy hygge photography aesthetic. Composition: Medium portrait showing upper body and cozy environment. Shallow depth of field with cabin softly blurred. Color palette: Cream and caramel knits, warm fireplace oranges, rich wood browns, soft winter whites. Photography style: Lifestyle cozy editorial. Shot on 50mm lens with warm natural lighting. Mood: Peaceful, warm, hygge, comforting. The perfect winter retreat moment.`,

  luxury_ski: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a glamorous luxury ski resort portrait. The person wears high-end winter fashion - elegant white or cream puffer jacket with fur trim, designer ski goggles resting on head, cashmere scarf. Sleek hair styled perfectly. Expression: Confident, glamorous, sophisticated with radiant smile. Eyes sparkle with winter excitement. Luxury lifestyle energy. Pose: Standing confidently with one hand adjusting goggles on head, other hand in jacket pocket. Elegant posture. Setting: Upscale ski resort terrace or lodge with snow-covered mountain peaks in background. Wooden lodge architecture. Clear blue sky. Fresh pristine snow. Apres-ski luxury atmosphere. Lighting: Bright crisp winter sunlight creating sharp highlights and shadows. Snow reflecting light for soft fill. Clear mountain air. Cinematic luxury travel photography. Composition: Medium portrait showing winter fashion and mountain backdrop. Shallow depth of field with mountains softly blurred. Color palette: Pristine whites and creams, luxury gold accents, clear blue sky, warm wood tones. Photography style: High-end travel editorial. Shot on 35mm lens with bright winter lighting. Mood: Glamorous, luxurious, aspirational. Winter fashion at its finest.`,

  winter_forest: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an enchanting winter forest portrait. The person wears a long wool coat in deep burgundy or forest green, fur-lined hood up or down, leather gloves, tall winter boots. Scarf wrapped warmly. Expression: Serene, wonder-filled, peaceful with soft smile. Eyes show magic and tranquility. Winter wonderland energy. Pose: Standing among snow-covered trees, one hand touching a snow-laden branch. Natural, graceful posture. Snow gently falling around them. Setting: Dense forest with snow-covered evergreen trees. Soft snowfall in air. Magical winter forest atmosphere. Morning or twilight blue hour lighting. Frosted branches creating natural frame. Lighting: Soft diffused daylight through snowy clouds. Cool blue winter tones with warm skin tone contrast. Subtle rim light from sky. Dreamy fairy tale photography aesthetic. Composition: Medium portrait showing person and magical forest environment. Snow-covered trees frame subject. Shallow depth of field with forest softly blurred. Color palette: Deep winter coat colors, white snow, forest greens, cool blue atmosphere, warm skin tones. Photography style: Fantasy winter editorial. Shot on 50mm lens with natural winter light. Mood: Magical, serene, enchanting. A fairy tale winter moment.`,

  mountain_peak: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an epic mountain peak winter portrait. The person wears technical outdoor gear - insulated jacket in bold colors (red, orange, or blue), winter beanie or hood, neck gaiter pulled down, sporty sunglasses. Expression: Triumphant, exhilarated, accomplished with proud smile. Eyes show adventure and achievement. Mountain conquest energy. Pose: Standing at summit with arms raised or spread wide in victory. Confident adventurer stance. Or pointing to distant peaks. Setting: Mountain summit or high ridge with dramatic snowy peaks stretching to horizon. Clear blue sky. Vast winter landscape below. Epic scale. Wind-blown snow. Lighting: Bright high-altitude sunlight creating strong contrast. Clear crisp air. Dramatic shadows on snow. Golden hour possible for warm tones. Adventure photography aesthetic. Composition: Wide to medium portrait showing both person and epic mountain landscape. Sharp focus on adventurer with majestic peaks behind. Color palette: Bold jacket colors, brilliant white snow, deep blue sky, mountain grey, golden sunlight. Photography style: Adventure editorial. Shot on 24-35mm lens with dramatic landscape. Mood: Epic, adventurous, triumphant. The thrill of mountain achievement.`,

  winter_city: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an atmospheric urban winter evening portrait. The person wears stylish winter city fashion - wool peacoat or trench in charcoal or camel, elegant scarf, leather gloves, stylish beanie or no hat with hair styled. Expression: Thoughtful, romantic, urban sophistication with subtle smile. Eyes show city energy and warmth. Metropolitan winter vibe. Pose: Walking through city street or standing under streetlight. One hand in coat pocket, other adjusting scarf. Natural urban movement. Setting: City street at dusk with holiday lights or street lamps glowing. Light snow falling. Urban architecture in background. Bokeh of city lights. Shop windows glowing warm. Lighting: Warm street lamp creating key light. Cool winter blue hour ambient. City lights creating colorful bokeh. Cinematic urban photography aesthetic. Falling snow catching light. Composition: Medium portrait with urban environment and lights in background. Shallow depth of field with bokeh city lights. Color palette: Warm street light golds, cool winter blues, city light colors, elegant coat colors, white snow. Photography style: Urban lifestyle editorial. Shot on 50mm lens with city night lighting. Mood: Romantic, sophisticated, urban. The magic of winter city nights.`,

  // CLASSY STYLES
  black_tie: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an ultra-sophisticated black tie portrait. The person wears either a sharp black tuxedo with bow tie, white dress shirt, cufflinks OR an elegant black evening gown with jewelry. Expression: Confident, refined, elegant with subtle sophisticated smile. Eyes convey class and poise. Red carpet energy. Pose: Standing with confident posture. For tuxedo: adjusting bow tie or cufflinks, hand in pocket. For gown: hand on hip or elegant stance. Setting: Luxury hotel ballroom, grand staircase, or upscale venue. Rich architectural details. Chandeliers softly glowing in background. Elegant drapery or marble. Lighting: Elegant warm lighting from chandeliers creating soft glamorous glow. Rim light for separation. Professional event photography aesthetic. Composition: Full length or 3/4 portrait showing formal wear. Sharp focus on subject with elegant venue softly blurred. Color palette: Deep blacks, crisp whites, warm gold lighting, rich jewel tones from venue. Photography style: High-end formal event editorial. Shot on 85mm lens with elegant lighting. Mood: Sophisticated, timeless, elegant. The epitome of formal elegance.`,

  evening_gown: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a stunning evening gown portrait. The woman wears a floor-length evening gown in jewel tones - emerald, sapphire, ruby red, or classic black. Off-shoulder or elegant neckline. Statement jewelry - diamonds or elegant pieces. Hair in elegant updo or flowing waves. Expression: Glamorous, confident, radiant with captivating smile. Eyes sparkle with elegance. Red carpet goddess energy. Pose: Hand on hip, other hand delicately holding gown. Elegant S-curve posture. Or dramatic pose with gown flowing. Setting: Grand staircase, luxury hotel, or elegant backdrop. Rich velvet curtains or architectural columns. Golden details and luxury elements. Lighting: Dramatic Hollywood lighting with soft key light. Rim light creating glamorous glow. Professional fashion lighting. Cinematic red carpet aesthetic. Composition: Full length portrait showing gown's elegance. Sharp focus with elegant background softly blurred. Color palette: Rich gown color, warm golden lighting, luxury backdrop, statement jewelry sparkle. Photography style: High-fashion evening wear editorial. Shot on 85mm lens with glamorous lighting. Mood: Glamorous, stunning, show-stopping. Red carpet perfection.`,

  gentleman_study: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a distinguished gentleman portrait in a study. The person wears a three-piece suit in charcoal or navy, pocket watch chain visible, leather dress shoes. Holding whiskey glass or book. Expression: Confident, distinguished, intelligent with knowing smile. Eyes show wisdom and refinement. Classic gentleman energy. Pose: Seated in leather armchair or standing by bookshelf. One hand holding whiskey tumbler, other resting on chair arm or holding book. Refined posture. Setting: Rich wood-paneled study or library. Floor-to-ceiling bookshelves filled with leather-bound books. Mahogany desk. Green banker's lamp. Persian rug. Fireplace. Classic oil paintings. Lighting: Warm ambient lighting from table lamps and fireplace. Soft golden tones. Rich shadows. Classic portrait photography aesthetic. Composition: Medium portrait showing gentleman and elegant study environment. Shallow depth of field with library softly blurred. Color palette: Rich browns of leather and wood, deep suit colors, warm golden lighting, green lamp accents. Photography style: Classic gentleman editorial. Shot on 50mm lens with warm interior lighting. Mood: Distinguished, refined, timeless. Old-world sophistication.`,

  champagne_celebration: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an elegant celebration portrait. The person wears sophisticated cocktail attire - sleek dress or sharp suit in elegant colors. Holding champagne flute. Statement jewelry or elegant accessories. Expression: Joyful, elegant, celebrating with radiant smile. Eyes sparkle with happiness. Sophisticated celebration energy. Pose: Holding champagne flute elegantly, perhaps mid-toast. Confident celebratory posture. Other hand on hip or holding champagne bottle. Setting: Luxury penthouse, rooftop venue, or elegant party space. Soft bokeh of city lights or party lights in background. Elegant modern decor. Champagne bottles and glasses visible. Lighting: Warm ambient party lighting with soft golden tones. Bokeh lights creating elegant atmosphere. Rim light for glamorous glow. Lifestyle celebration photography. Composition: Medium portrait showing celebration and elegant environment. Shallow depth of field with party lights as beautiful bokeh. Color palette: Champagne gold, elegant clothing colors, warm lighting, sparkling highlights. Photography style: Luxury lifestyle editorial. Shot on 50mm lens with celebration lighting. Mood: Joyful, sophisticated, celebratory. The art of elegant celebration.`,

  art_museum: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a sophisticated art museum portrait. The person wears elegant contemporary fashion - tailored suit, designer dress, or chic art gallery outfit in black, white, or minimalist colors. Stylish accessories. Expression: Thoughtful, cultured, sophisticated with subtle smile. Eyes show intelligence and appreciation for art. Cultured collector energy. Pose: Standing contemplating artwork, hand touching chin thoughtfully. Or walking through gallery. Elegant cultured posture. Setting: Modern art museum or gallery with white walls. Abstract art pieces visible in background. Clean minimalist architecture. Gallery lighting. High ceilings. Polished floors reflecting light. Lighting: Museum gallery lighting - clean, bright, even illumination. Soft overhead spotlights. Clean shadows. Professional museum photography aesthetic. Composition: Medium portrait showing person and gallery environment. Sharp focus with artwork softly visible behind. Color palette: Clean whites, elegant blacks, minimalist greys, pops of color from artwork. Photography style: Contemporary art editorial. Shot on 35mm lens with gallery lighting. Mood: Sophisticated, cultured, refined. The epitome of contemporary elegance.`,

  // ADVENTURE STYLES
  mountain_hiking: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an epic mountain hiking portrait. The person wears technical hiking gear - moisture-wicking shirt, hiking pants, backpack with visible straps, hiking boots, baseball cap or sun hat. Trekking poles in hand. Expression: Determined, exhilarated, free with genuine smile. Eyes show adventure spirit. Mountain explorer energy. Pose: Standing on mountain trail with backpack, trekking poles in use. Confident hiker stance. Or sitting on rock taking a break. Setting: Mountain trail with dramatic peaks in background. Rolling hills or valleys below. Clear sky. Rocky terrain. Alpine wildflowers possible. Vast wilderness. Lighting: Natural mountain sunlight creating strong directional light. Clear air. Blue sky. Golden hour possible for warm tones. Adventure photography aesthetic. Composition: Wide to medium shot showing hiker and epic landscape. Sharp focus on person with mountains majestically behind. Color palette: Earth tones of hiking gear, mountain greys and greens, blue sky, natural landscape colors. Photography style: Outdoor adventure editorial. Shot on 24-35mm lens. Mood: Free, adventurous, inspiring. The call of the mountains.`,

  safari_expedition: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create an adventurous safari portrait. The person wears classic safari outfit - khaki or olive shirt with rolled sleeves, safari pants, wide-brimmed safari hat, leather boots. Binoculars around neck or camera with telephoto lens. Expression: Excited, adventurous, observant with wide smile. Eyes show thrill of wildlife discovery. Explorer energy. Pose: Standing with binoculars raised or holding camera. Adventurous safari stance. Or sitting in safari vehicle. Setting: African savanna with acacia trees. Golden grasslands stretching to horizon. Safari vehicle partially visible. Warm African landscape. Golden hour light. Dust particles in air. Lighting: Warm golden hour African sunlight. Rich warm tones. Strong directional light. Dust catching light. Cinematic safari photography aesthetic. Composition: Medium portrait showing safari outfit and African landscape. Shallow depth of field with savanna softly blurred. Color palette: Khaki safari colors, golden grasslands, warm African sunset, earth tones. Photography style: Adventure travel editorial. Shot on 35mm lens with golden hour light. Mood: Adventurous, exotic, thrilling. The romance of African safari.`,

  jungle_explorer: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a jungle explorer portrait. The person wears expedition gear - cargo shirt in olive or tan, adventure pants with multiple pockets, explorer hat or bandana, sturdy boots. Machete in holder or backpack straps visible. Expression: Adventurous, determined, spirited with confident smile. Eyes show exploration passion. Indiana Jones energy. Pose: Standing in jungle clearing, hand on backpack strap. Explorer stance. Or examining tropical plant with curiosity. Setting: Lush tropical rainforest with dense vegetation. Massive trees and vines. Tropical foliage. Dappled sunlight through canopy. Mist in air. Exotic plants and ferns. Lighting: Filtered jungle light through canopy creating dappled patterns. Warm green-tinted ambient light. Rays of light breaking through trees. Adventure photography aesthetic. Composition: Medium portrait showing explorer and lush jungle environment. Sharp focus with jungle softly blurred behind. Color palette: Rich jungle greens, earth tones of explorer gear, warm filtered sunlight, deep shadows. Photography style: Expedition adventure editorial. Shot on 35mm lens with natural jungle light. Mood: Adventurous, mysterious, exploratory. The thrill of jungle discovery.`,

  canyon_adventure: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a dramatic canyon adventure portrait. The person wears desert adventure gear - light breathable shirt, adventure pants, sun protection hat or bandana, hiking boots, sunglasses on or hanging from shirt. Hydration pack visible. Expression: Awestruck, adventurous, free with exhilarated smile. Eyes show wonder at natural beauty. Desert explorer energy. Pose: Standing on canyon edge or rock formation. Arms spread or pointing to view. Confident adventure stance. Setting: Dramatic red rock canyon with layered sandstone formations. Vast desert landscape. Clear blue sky. Iconic Southwest scenery. Ancient rock formations creating natural sculptures. Lighting: Bright desert sunlight creating strong contrast. Deep blue sky. Rich red rocks glowing. Clear dry air. Golden hour possible for magical light. Landscape photography aesthetic. Composition: Wide to medium shot showing adventurer and epic canyon landscape. Sharp focus with dramatic formations behind. Color palette: Rich red and orange rocks, bright blue sky, tan adventure gear, golden sunlight. Photography style: Adventure landscape editorial. Shot on 24-35mm lens. Mood: Awe-inspiring, free, adventurous. The majesty of desert canyons.`,

  desert_wanderer: `Keep the facial features of the person in the uploaded image exactly consistent. Preserve 100% accuracy of the face from the reference image. Important: do not change the face. Create a mystical desert wanderer portrait. The person wears flowing adventure clothing - light linen shirt or tunic, comfortable adventure pants, desert scarf draped around shoulders or head, sturdy boots. Backpack visible. Expression: Peaceful, contemplative, free with serene smile. Eyes show desert wisdom and freedom. Nomad wanderer energy. Pose: Standing on sand dune with wind blowing clothing gently. Hand shielding eyes from sun. Or walking through dunes. Nomadic posture. Setting: Endless rolling sand dunes stretching to horizon. Pristine golden sand. Clear sky - either bright blue or warm sunset. Rippled sand patterns. Vast emptiness and beauty. Lighting: Golden hour desert light creating warm magical glow. Long shadows on dunes. Soft warm tones. Or bright midday creating strong contrast. Cinematic desert photography. Composition: Medium to wide shot showing wanderer and endless dunes. Sharp focus with dunes creating beautiful layers behind. Color palette: Golden sand, warm sunset colors, light adventure clothing, rich blue sky. Photography style: Cinematic adventure editorial. Shot on 35mm lens with golden hour light. Mood: Peaceful, mystical, free. The serenity of endless desert.`,

  // Legacy styles (keep for backwards compatibility)
  corporate: `Keep the facial features of the person in the uploaded image exactly consistent. Dress them in a professional navy blue business suit with a white shirt, similar to a corporate executive. Background: Place the subject against a clean, solid dark gray studio photography backdrop. The background should have a subtle gradient, slightly lighter behind the subject and darker towards the edges (vignette effect). There should be no other objects. Photography Style: Shot on a Sony A7III with an 85mm f/1.4 lens, creating a flattering portrait compression. Lighting: Use a classic three-point lighting setup. The main key light should create soft, defining shadows on the face. A subtle rim light should separate the subject's shoulders and hair from the dark background. Crucial Details: Render natural skin texture with visible pores, not an airbrushed look. Add natural catchlights to the eyes. The fabric of the suit should show a subtle wool texture. Final image should be an ultra-realistic, 8k professional headshot.`,

  creative: `Keep the facial features of the person in the uploaded image exactly consistent. Dress them in smart casual attire - a well-fitted blazer over a quality solid-color t-shirt. Background: Modern minimalist office or creative studio environment with soft natural window light. Blurred background with subtle hints of contemporary furniture or plants. Photography Style: Shot on a Canon EOS R5 with a 50mm f/1.2 lens for a natural perspective. Lighting: Soft, diffused window lighting from one side, creating gentle shadows and a warm, approachable feel. Crucial Details: Natural, relaxed expression. Authentic skin texture with a healthy glow. Modern, editorial style portrait suitable for creative industry professionals. Colors should be warm and inviting. Final image should be high-quality editorial portrait.`,

  friendly: `Keep the facial features of the person in the uploaded image exactly consistent. Dress them in a light blue oxford shirt, no jacket - professional yet approachable. Background: Warm neutral background with a soft, seamless gradient. Cream to light tan tones. Photography Style: Shot on a Nikon Z8 with an 85mm f/1.8 lens for flattering compression. Lighting: Soft, diffused key light creating minimal shadows. Fill light for an even, welcoming look. A subtle warmth in the lighting temperature. Crucial Details: Genuine, warm smile showing approachability. Natural skin tones with warm undertones. Eyes should have clear catchlights and appear engaged. Professional yet friendly headshot perfect for LinkedIn or company profiles. Final image should be a professional, approachable headshot.`
};

export async function generatePortrait(
  imageBase64: string,
  styleKey: string,
  mimeType: string = 'image/jpeg',
  customPrompt?: string,
  editPrompt?: string
): Promise<string> {
  let prompt: string;
  
  // If edit mode, use edit prefix with the edit prompt
  if (styleKey === 'edit' && editPrompt) {
    prompt = EDIT_PREFIX + editPrompt;
  }
  // If custom style, require custom prompt
  else if (styleKey === 'custom') {
    if (!customPrompt || customPrompt.trim().length === 0) {
      throw new Error('Custom prompt is required for custom style');
    }
    prompt = FACE_CONSISTENCY_PREFIX + customPrompt;
  } else {
    // Use predefined style prompt
    prompt = STYLE_PROMPTS[styleKey];
  if (!prompt) {
    throw new Error(`Unknown style: ${styleKey}`);
    }
  }

  // Convert base64 to data URI for Replicate
  const imageDataUri = `data:${mimeType};base64,${imageBase64}`;

  // Prepare input for Replicate (defined outside try block for retry access)
  const replicateInput = {
    prompt: prompt,
    image_input: [imageDataUri], // nano-banana expects image_input as array
    aspect_ratio: "match_input_image",
    output_format: "jpg"
  };

  try {
    console.log('Starting Replicate generation with nano-banana...');
    console.log('Style:', styleKey);

    // Run the Nano Banana model on Replicate
    const output = await replicate.run(MODEL_ID as `${string}/${string}`, {
      input: replicateInput
    });

    console.log('Replicate output type:', typeof output);
    console.log('Replicate output:', output);

    // Handle streaming output from Replicate (Uint8Array chunks)
    if (output && Symbol.asyncIterator in Object(output)) {
      console.log('Handling async iterator output...');
      const chunks: Uint8Array[] = [];
      for await (const chunk of output as AsyncIterable<Uint8Array>) {
        chunks.push(chunk);
      }
      // Combine all chunks into a single buffer
      const totalLength = chunks.reduce((acc, chunk) => acc + chunk.length, 0);
      const combined = new Uint8Array(totalLength);
      let offset = 0;
      for (const chunk of chunks) {
        combined.set(chunk, offset);
        offset += chunk.length;
      }
      const base64 = Buffer.from(combined).toString('base64');
      console.log('Generated base64 length:', base64.length);
      return base64;
    }

    // Handle array output (URLs)
    if (Array.isArray(output) && output.length > 0) {
      console.log('Handling array output...');
      const resultUrl = output[0];
      const response = await fetch(resultUrl);
      const arrayBuffer = await response.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString('base64');
      return base64;
    }

    // Handle string output (URL)
    if (typeof output === 'string') {
      console.log('Handling string output...');
      const response = await fetch(output);
      const arrayBuffer = await response.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString('base64');
      return base64;
    }

    // Handle object with output property
    if (output && typeof output === 'object' && 'output' in output) {
      console.log('Handling object output...');
      const resultUrl = (output as any).output;
    const response = await fetch(resultUrl);
    const arrayBuffer = await response.arrayBuffer();
    const base64 = Buffer.from(arrayBuffer).toString('base64');
      return base64;
    }

    console.error('Unhandled output format:', output);
    throw new Error('Unexpected output format from Replicate');
  } catch (error: any) {
    // Sanitize error logging to avoid leaking tokens
    console.error('Replicate generation error:', error.message);
    if (error.response) {
      console.error('Replicate API Status:', error.response.status, error.response.statusText);
    }
    
    // Check for rate limiting (429 status)
    if (error.message && error.message.includes('429')) {
      // Extract retry_after value from error message if available
      const retryMatch = error.message.match(/retry_after[":]+\s*(\d+)/);
      const retryAfter = retryMatch ? parseInt(retryMatch[1]) : 3; // Default to 3 seconds
      
      console.log(`⏳ Rate limited by Replicate. Waiting ${retryAfter} seconds before retry...`);
      
      // Wait for the specified retry_after duration
      await new Promise(resolve => setTimeout(resolve, retryAfter * 1000));
      
      // Retry the request once after waiting
      console.log('🔄 Retrying after rate limit wait...');
      try {
        const retryPrediction = await replicate.run(MODEL_ID, { input: replicateInput });
        
        // Process the retry output (same logic as above)
        if (retryPrediction && Symbol.asyncIterator in Object(retryPrediction)) {
          const chunks: Uint8Array[] = [];
          for await (const chunk of retryPrediction as AsyncIterable<Uint8Array>) {
            chunks.push(chunk);
          }
          const totalLength = chunks.reduce((acc, chunk) => acc + chunk.length, 0);
          const combined = new Uint8Array(totalLength);
          let offset = 0;
          for (const chunk of chunks) {
            combined.set(chunk, offset);
            offset += chunk.length;
          }
          return Buffer.from(combined).toString('base64');
        }
        
        if (Array.isArray(retryPrediction) && retryPrediction.length > 0) {
          const response = await fetch(retryPrediction[0]);
          const arrayBuffer = await response.arrayBuffer();
          return Buffer.from(arrayBuffer).toString('base64');
        }
        
        if (typeof retryPrediction === 'string') {
          const response = await fetch(retryPrediction);
          const arrayBuffer = await response.arrayBuffer();
          return Buffer.from(arrayBuffer).toString('base64');
        }
        
        throw new Error('Unexpected output format from Replicate after retry');
      } catch (retryError: any) {
        console.error('❌ Retry failed:', retryError.message);
        throw new Error(`Image generation failed after retry: ${retryError.message}`);
      }
    }
    
    // Check for content moderation errors (E005 - sensitive content)
    if (error.message && error.message.includes('E005')) {
      throw new Error('CONTENT_POLICY_VIOLATION: Your prompt was flagged by our content filter. Please ensure your request follows community guidelines and does not include inappropriate, explicit, or sensitive content.');
    }
    
    // Check for other common Replicate errors
    if (error.message && error.message.includes('flagged as sensitive')) {
      throw new Error('CONTENT_POLICY_VIOLATION: Content detected as sensitive. Please try a different prompt that follows our community guidelines.');
    }
    
    throw new Error(`Image generation failed: ${error.message}`);
  }
}

export function getAvailableStyles() {
  // Only return the main 3 styles, not legacy ones
  const mainStyles = ['business', 'emotional_film', 'victoria_secret'];
  
  return mainStyles.map(key => ({
    key,
    name: getStyleName(key),
    description: getStyleDescription(key)
  }));
}

function getStyleName(styleKey: string): string {
  const names: Record<string, string> = {
    business: 'Business Photo',
    emotional_film: 'Emotional Film Photography',
    victoria_secret: "Victoria's Secret Photoshoot",
    corporate: 'Corporate Executive',
    creative: 'Creative Professional',
    friendly: 'Friendly Business'
  };
  return names[styleKey] || styleKey;
}

function getStyleDescription(styleKey: string): string {
  const descriptions: Record<string, string> = {
    business: 'Professional corporate headshot - perfect for LinkedIn and company profiles',
    emotional_film: 'Cinematic film look with rich colors and emotional depth',
    victoria_secret: 'Glamorous high-fashion runway and editorial style',
    corporate: 'Professional navy suit with studio backdrop - perfect for executives',
    creative: 'Smart casual with modern office setting - ideal for creative professionals',
    friendly: 'Approachable oxford shirt look - great for LinkedIn and team pages'
  };
  return descriptions[styleKey] || '';
}
